# ==============================================================================
# Apache VirtualHosts para Grandprix
# ==============================================================================

# 1. Sitio Web Público (Dominio Raíz) -> /var/www/html/public
<VirtualHost *:80>
    ServerName grandprixvzla.com
    ServerAlias www.grandprixvzla.com
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    LogLevel warn
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>

# 2. Dashboard Administrativo -> /var/www/html
<VirtualHost *:80>
    ServerName dashboard.grandprixvzla.com
    ServerAlias localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    LogLevel warn
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
