<?php
declare(strict_types=1);
$lock=__DIR__.'/config/install.lock';if(!file_exists($lock)){header('Location: install/');exit;}
require_once __DIR__.'/lib/bootstrap.php';gp_start_session();gp_require_admin(false);
$admin=gp_current_admin();if(!gp_user_can('gps.monitor.view')&&!gp_user_can('gps.vehicles.view')&&!gp_user_can('gps.alerts.view')){http_response_code(403);exit('Tu usuario no tiene acceso al área de monitoreo GPS.');}$adminName=(string)($admin['name']?:'Administrador GRANDPRIX');$adminRole=(string)($admin['role']?:'Administrador');$parts=preg_split('/\s+/',trim($adminName))?:[];$initials='';foreach(array_slice($parts,0,2) as $part)$initials.=mb_strtoupper(mb_substr($part,0,1));if($initials==='')$initials='GP';$csrf=gp_csrf_token();
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#061a31"><title>GRANDPRIX · Monitoreo GPS</title><link rel="icon" href="assets/grandprix-logo.png"><link rel="stylesheet" href="assets/vendor/maplibre-gl.css?v=5.24.0"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/app.css?v=11.0.0"><link rel="stylesheet" href="assets/premium.css?v=11.0.0"><link rel="stylesheet" href="assets/satellite-pro.css?v=7.2.0"><link rel="stylesheet" href="assets/v72-admin.css?v=7.2.0"><link rel="stylesheet" href="assets/finance-users-v8.css?v=18.0.0"></head><body class="workspace-monitor">
<div class="app"><aside class="sidebar" id="sidebar"><button class="close-side" onclick="toggleMenu()"><i class="fa-solid fa-xmark"></i></button><div class="brand"><img src="assets/grandprix-logo.png" alt="Grandprix"></div><div class="product"><small>GRANDPRIX MONITOREO</small><b>Seguridad GPS en vivo</b></div><a class="workspace-switch" href="index.php"><i class="fa-solid fa-building-columns"></i><span><b>Volver a Administración</b><small>Finanzas, clientes y créditos</small></span><i class="fa-solid fa-arrow-right"></i></a><nav id="nav"></nav><div class="central"><i></i><span><b>Central GPS activa</b><small>Webhook + canal en vivo</small></span></div><div class="profile"><span><?=htmlspecialchars($initials)?></span><div><b><?=htmlspecialchars($adminName)?></b><small><?=htmlspecialchars($adminRole)?></small></div><a href="logout.php" title="Cerrar sesión" style="color:inherit"><i class="fa-solid fa-right-from-bracket"></i></a></div></aside>
<main><header><div class="title-wrap"><button class="menu" onclick="toggleMenu()"><i class="fa-solid fa-bars"></i></button><div><small id="breadcrumb">GRANDPRIX / Monitoreo GPS</small><h1 id="pageTitle">Monitoreo GPS en vivo</h1></div></div><div class="head-actions"><span class="live"><i></i> DATOS EN VIVO</span><a class="head-link admin" href="index.php"><i class="fa-solid fa-building-columns"></i><span>Administración</span></a><button onclick="openQuick()"><i class="fa-solid fa-shield-halved"></i><span>Acción GPS</span></button></div></header><div id="view"></div></main></div>
<nav class="mobile-nav"><button data-go="mapa"><i class="fa-solid fa-map-location-dot"></i><span>Mapa</span></button><button data-go="dispositivos"><i class="fa-solid fa-sim-card"></i><span>GPS</span></button><button data-go="grupos"><i class="fa-solid fa-layer-group"></i><span>Grupos</span></button><button data-go="historial"><i class="fa-solid fa-route"></i><span>Historial</span></button><button onclick="toggleMenu()"><i class="fa-solid fa-grip"></i><span>Más</span></button></nav>
<div class="overlay" id="quick"><div class="modal"><button class="modal-x" onclick="closeModal('quick')"><i class="fa-solid fa-xmark"></i></button><span class="eyebrow">SEGURIDAD GPS</span><h2>Acciones de monitoreo</h2><div class="quick-grid"><button onclick="closeModal('quick');navigate('mapa')"><i class="fa-solid fa-map-location-dot"></i><b>Ver mapa</b></button><button onclick="closeModal('quick');navigate('comandos')"><i class="fa-solid fa-terminal"></i><b>Centro de comandos</b></button><button onclick="closeModal('quick');navigate('geocercas')"><i class="fa-solid fa-draw-polygon"></i><b>Geocercas</b></button><button onclick="closeModal('quick');navigate('historial')"><i class="fa-solid fa-route"></i><b>Historial</b></button></div></div></div>
<div class="overlay" id="danger"><div class="modal danger-modal"><button class="modal-x" onclick="closeModal('danger')"><i class="fa-solid fa-xmark"></i></button><div class="danger-icon"><i class="fa-solid fa-power-off"></i></div><span class="eyebrow">COMANDO PROTEGIDO</span><h2>Corte remoto seguro</h2><p>La orden se gestiona desde el Centro de comandos y solo se enviará con las validaciones de seguridad existentes.</p><div class="modal-actions"><button onclick="closeModal('danger')">Cancelar</button><button class="red" onclick="closeModal('danger');navigate('comandos')">Abrir centro seguro</button></div></div></div>
<div id="toast"></div><script>window.GRANDPRIX={area:'monitor',csrf:<?=json_encode($csrf)?>,version:<?=json_encode(gp_release())?>,traccarApi:'api/traccar.php',commandApi:'api/commands.php',customerAdminApi:'api/customer-admin.php',financeApi:'api/finance-v8.php',usersApi:'api/admin-users-v8.php',admin:<?=json_encode($admin,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>};</script><script src="assets/vendor/maplibre-gl.js?v=5.24.0"></script><script src="assets/vendor/pusher.min.js?v=8.6.0"></script><script src="assets/app.js?v=18.0.0"></script><script src="assets/realtime.js?v=7.2.0"></script><script src="assets/satellite-pro.js?v=7.2.0"></script><script src="assets/v72-admin.js?v=7.2.0"></script><script src="assets/finance-users-v8.js?v=18.0.0"></script><script src="assets/monitor-v11.js?v=11.0.0"></script></body></html>
